import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  container: {},
  content: {
    height: 40,
    padding: 5,
    borderRadius: 40,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'white',
    shadowColor: '#00000040',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
    paddingRight: 10,
  },
  contentNoShadow: {
    shadowOpacity: 0,
    shadowRadius: 0,
    paddingRight: 0,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 10,
  },
  logoContainer: {
    width: 24,
    height: 24,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'white',
    borderRadius: 24,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
    marginLeft: 7,
    marginRight: 7,
  },
  logoWrap: {
    width: 24,
    height: 24,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'white',
    borderRadius: 24,
    overflow: 'hidden',
  },
  logo: {
    width: 20,
    height: 20,
    resizeMode: 'contain',
  },
  name: {
    fontSize: 18,
    color: '#181818',
  },
  nameSelect: {
    color: '#E8006F',
    marginLeft: 7,
  },
  modalWrap: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  modal: {
    width: '90%',
    height: '70%',
    borderRadius: 10,
    backgroundColor: 'white',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
    paddingVertical: 20,
  },
  modalTitle: {
    fontSize: 18,
    color: '#181818',
    marginHorizontal: 20,
  },
  item: {
    flexDirection: 'row',
    paddingVertical: 5,
    paddingHorizontal: 20,
    alignItems: 'center',
  },
  itemLogoContainer: {
    width: 30,
    height: 30,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'white',
    borderRadius: 24,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
    marginRight: 7,
  },
  itemLogoWrap: {
    width: 30,
    height: 30,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'white',
    borderRadius: 24,
    overflow: 'hidden',
  },
  itemLogo: {
    width: 25,
    height: 25,
    resizeMode: 'contain',
  },
  helper: {
    fontSize: 14,
    color: '#18181850',
  },
  filterWrap: {
    marginVertical: 10,
    marginHorizontal: 20,
    height: 40,
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgb(229,229,229)',
    borderRadius: 20,
    paddingHorizontal: 20,
  },
  filter: {
    fontSize: 16,
    color: '#181818',
  },
});
