import {BaseCoin} from '@app/models/coinTypes';
import {NetworkName} from './enums';

export const DEFAULT_COINS: BaseCoin[] = [
  {
    id: 'usd-coin',
    name: 'USD Coin',
    symbol: 'usdc',
    contractAddress: '0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48',
    network: NetworkName.ethereum,
    enabled: true,
  },
  {
    id: 'ethereum',
    name: 'Ethereum',
    symbol: 'eth',
    contractAddress: NetworkName.ethereum,
    network: NetworkName.ethereum,
    enabled: true,
  },
  {
    id: 'usd-coin',
    name: 'USD Coin',
    symbol: 'usdc',
    contractAddress: '0x3c499c542cef5e3811e1192ce70d8cc03d5c3359',
    network: NetworkName.polygon,
    enabled: false,
  },
  {
    id: 'usd-coin',
    name: 'USD Coin (PoS)',
    symbol: 'usdc.e',
    contractAddress: '0x2791bca1f2de4661ed88a30c99a7a9449aa84174',
    network: NetworkName.polygon,
    enabled: false,
  },
  {
    id: 'matic-network',
    name: 'Polygon',
    symbol: 'matic',
    contractAddress: NetworkName.polygon,
    network: NetworkName.polygon,
    enabled: false,
  },
  {
    id: 'zilliqa',
    name: 'Zilliqa',
    symbol: 'zil',
    contractAddress: NetworkName.zilliqa,
    network: NetworkName.zilliqa,
    enabled: false,
  },
  {
    id: 'binancecoin',
    name: 'BNB',
    symbol: 'bnb',
    contractAddress: NetworkName.binance,
    network: NetworkName.binance,
    enabled: false,
  },
  {
    id: 'binancecoin',
    name: 'Smart Chain',
    symbol: 'bnb',
    contractAddress: NetworkName.binanceSmartChain,
    network: NetworkName.binanceSmartChain,
    enabled: false,
  },
  {
    id: 'solana',
    symbol: 'sol',
    name: 'Solana',
    contractAddress: NetworkName.solana,
    network: NetworkName.solana,
    enabled: false,
  },
  {
    id: 'avalanche-2',
    symbol: 'avax',
    name: 'Avax',
    contractAddress: NetworkName.avalanche,
    network: NetworkName.avalanche,
    enabled: false,
  },
];
