import {Currency} from '@app/models/currency';

export const currencies: Currency[] = [
  {cc: 'aud', name: 'Australian dollar', symbol: '$', type: 'popular'},
  {cc: 'cny', name: 'Chinese/Yuan renminbi', symbol: '¥', type: 'popular'},
  {cc: 'eur', name: 'European Euro', symbol: '€', type: 'popular'},
  {cc: 'gbp', name: 'British pound', symbol: '£', type: 'popular'},
  {cc: 'usd', name: 'United States dollar', symbol: '$', type: 'popular'},
  {cc: 'btc', name: 'Bitcoin', symbol: 'eth', type: 'popular'},
  {cc: 'eth', name: 'Ethereum', symbol: 'eth', type: 'popular'},
  {cc: 'bnb', name: 'BNB', symbol: 'bnb', type: 'popular'},
  {cc: 'ltc', name: 'Litecoin', symbol: 'ltc', type: 'crypto'},
  {cc: 'bch', name: 'Bitcoin Cash', symbol: 'bch', type: 'crypto'},
  {cc: 'eos', name: 'EOS', symbol: 'eos', type: 'crypto'},
  {cc: 'xrp', name: 'XRP', symbol: 'xrp', type: 'crypto'},
  {cc: 'xlm', name: 'Stellar', symbol: 'xlm', type: 'crypto'},
  {cc: 'link', name: 'Chainlink', symbol: 'link', type: 'crypto'},
  {cc: 'dot', name: 'Polkadot', symbol: 'dot', type: 'crypto'},
  {cc: 'yfi', name: 'yearn.finance', symbol: 'yfi', type: 'crypto'},
  {cc: 'sats', name: 'Baby Satoshi', symbol: 'sats', type: 'crypto'},
  {cc: 'bits', name: 'Bit', symbol: 'bits', type: 'crypto'},
  {cc: 'aed', name: 'UAE dirham', symbol: 'د.إ;', type: 'world'},
  {cc: 'ars', name: 'Argentine peso', symbol: '$', type: 'world'},
  {cc: 'bdt', name: 'Bangladeshi taka', symbol: '৳', type: 'world'},
  {cc: 'bhd', name: 'Bahraini dinar', symbol: '.د.ب', type: 'world'},
  {cc: 'bmd', name: 'Bermudian dollar', symbol: 'BD$', type: 'world'},
  {cc: 'brl', name: 'Brazilian real', symbol: 'R$', type: 'world'},
  {cc: 'cad', name: 'Canadian dollar', symbol: '$', type: 'world'},
  {cc: 'chf', name: 'Swiss franc', symbol: 'Fr.', type: 'world'},
  {cc: 'clp', name: 'Chilean peso', symbol: '$', type: 'world'},
  {cc: 'czk', name: 'Czech koruna', symbol: 'Kč', type: 'world'},
  {cc: 'dkk', name: 'Danish krone', symbol: 'Kr', type: 'world'},
  {cc: 'hkd', name: 'Hong Kong dollar', symbol: 'HK$', type: 'world'},
  {cc: 'huf', name: 'Hungarian forint', symbol: 'Ft', type: 'world'},
  {cc: 'idr', name: 'Indonesian rupiah', symbol: 'Rp', type: 'world'},
  {cc: 'ils', name: 'Israeli new sheqel', symbol: '₪', type: 'world'},
  {cc: 'inr', name: 'Indian rupee', symbol: '₹', type: 'world'},
  {cc: 'jpy', name: 'Japanese yen', symbol: '¥', type: 'world'},
  {cc: 'krw', name: 'South Korean won', symbol: 'W', type: 'world'},
  {cc: 'kwd', name: 'Kuwaiti dinar', symbol: 'KWD', type: 'world'},
  {cc: 'lkr', name: 'Sri Lankan rupee', symbol: 'Rs', type: 'world'},
  {cc: 'mmk', name: 'Myanma kyat', symbol: 'K', type: 'world'},
  {cc: 'mxn', name: 'Mexican peso', symbol: '$', type: 'world'},
  {cc: 'myr', name: 'Malaysian ringgit', symbol: 'RM', type: 'world'},
  {cc: 'ngn', name: 'Nigerian naira', symbol: '₦', type: 'world'},
  {cc: 'nok', name: 'Norwegian krone', symbol: 'kr', type: 'world'},
  {cc: 'nzd', name: 'New Zealand dollar', symbol: 'NZ$', type: 'world'},
  {cc: 'php', name: 'Philippine peso', symbol: '₱', type: 'world'},
  {cc: 'pkr', name: 'Pakistani rupee', symbol: 'Rs.', type: 'world'},
  {cc: 'pln', name: 'Polish zloty', symbol: 'zł', type: 'world'},
  {cc: 'rub', name: 'Russian ruble', symbol: 'R', type: 'world'},
  {cc: 'sar', name: 'Saudi riyal', symbol: 'SR', type: 'world'},
  {cc: 'sek', name: 'Swedish krona', symbol: 'kr', type: 'world'},
  {cc: 'sgd', name: 'Singapore dollar', symbol: 'S$', type: 'world'},
  {cc: 'thb', name: 'Thai baht', symbol: '฿', type: 'world'},
  {cc: 'try', name: 'Turkish new lira', symbol: 'TRY', type: 'world'},
  {cc: 'twd', name: 'New Taiwan dollar', symbol: 'NT$', type: 'world'},
  {cc: 'uah', name: 'Ukrainian hryvnia', symbol: 'UAH', type: 'world'},
  {cc: 'vnd', name: 'Vietnamese dong', symbol: '₫', type: 'world'},
  {cc: 'xdr', name: 'Special Drawing Rights', symbol: 'SDR', type: 'world'},
  {cc: 'zar', name: 'South African rand', symbol: 'R', type: 'world'},
];
