export const wyreCredentials = {
  accountId: 'AC_UFU3PMH3CJM',
  secretKey: 'TEST-AK-QF3W8TG4-BC8C4HE7-GPJL22LY-ULCEH4JN',
};

// TEST-AK-TZACXP9T-C6U4RQ7B-PRHCEGNH-MAZEJNRD
// TEST-SK-ANDHRMAN-MERGW863-YVYDGYJQ-XNCYQJ73
